
[window]

opacity = 0.94

padding.x = 8
padding.y = 8

decorations = "Full"

startup_mode = "Windowed"

option_as_alt = "Both"

blur = true

dimensions = { columns = 155, lines = 60 }

[font]

normal.family = "BlexMono NF"

size = 12.0

[cursor]

style.blinking = "On"

style.shape = "Beam"

[mouse]

hide_when_typing = true

[env]

TERM = "xterm-256color"

[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]
