import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[window]

opacity = 0.95

padding.x = 8
padding.y = 8

decorations = "Full"

# not working on M1 mac
# blur = true

startup_mode = "Windowed"

option_as_alt = "Both"

[font]

normal.family = "BlexMono NF"

size = 12.0

[cursor]

style.blinking = "On"

style.shape = "Beam"

[mouse]

hide_when_typing = true

[env]

TERM = "xterm-256color"
